spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=busbooking
    username: ${GOVDB_USER}
    password: ${GOVDB_PASSWORD}
    hikari:
      max-lifetime: 600000
      idle-timeout: 300
  jpa:
    hibernate:
      ddl-auto: create
